### ISSUE TITLE
Incompatibilidad entre dependencias de Guzzle

### ISSUE THREAD

**Issue by truchosky** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#244]
**Describe el bug**

Sencillo, el único plugin de pago que no funciona correctamente luego de instalar https://cl.wordpress.org/plugins/code-snippets/, el error:

2024-06-05T19:44:37+00:00 Crítico Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /xxx/wp-content/plugins/code-snippets-pro/vendor/guzzlehttp/guzzle/src/functions.php:61 CONTEXT: {"error":{"type":1,"file":"xxx\/wp-content\/plugins\/code-snippets-pro\/vendor\/guzzlehttp\/guzzle\/src\/functions.php","line":61},"backtrace":["","#0 xxx\/wp-content\/plugins\/transbank-webpay-plus-rest\/vendor\/guzzlehttp\/guzzle\/src\/HandlerStack.php(42): GuzzleHttp\\choose_handler()","#1 xxx\/wp-content\/plugins\/transbank-webpay-plus-rest\/vendor\/guzzlehttp\/guzzle\/src\/Client.php(65): GuzzleHttp\\HandlerStack::create()","#2 xxx\/wp-content\/plugins\/transbank-webpay-plus-rest\/vendor\/transbank\/transbank-sdk\/src\/Utils\/HttpClient.php(91): GuzzleHttp\\Client->__construct()","#3 xxx\/wp-content\/plugins\/transbank-webpay-plus-rest\/vendor\/transbank\/transbank-sdk\/src\/Utils\/HttpClient.php(52): Transbank\\Utils\\HttpClient->sendGuzzleRequest()","#4 xxx\/wp-content\/plugins\/transbank-webpay-plus-rest\/vendor\/transbank\/trans"]}

**Para reproducir**

Solo instalen el plugin de code snippets  https://cl.wordpress.org/plugins/code-snippets/

**Comportamiento observado**

Luego de la instalacion no se pueden procesar pagos en webpay

**Comportamiento esperado**

que siga funcionando como siempre, es el único plugin de pago, de los 8 que uso que tiene ese problema

**Capturas de pantalla**

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: [ej. 1.9.1]
- Woocommerce: [ej. 8.9.2]
- PHP: [ej. 7.4.33]

**Contexto adicional**

Agrega cualquier otro información sobre el problema aquí.

**Comment by mastudillot** [comment]
Hola, probaste usando la versión con la otra versión de guzzle?

**Comment by mastudillot** [comment]
Si usas el plugin que te dejo en el comentario no deberías tener problemas

**Comment by truchosky** [comment]
que ordinario, y para las actualizaciones tendré que subirlo siempre de forma manual?
